package com.example.Toastmasters.mapper;

import com.example.Toastmasters.dto.request.RolePreferenceRequestDTO;
import com.example.Toastmasters.dto.response.RolePreferenceResponseDTO;
import com.example.Toastmasters.entity.RolePreference;
import org.mapstruct.*;
import java.time.LocalDateTime;

@Mapper(componentModel = "spring")
public interface RolePreferenceMapper {

    RolePreferenceResponseDTO toResponseDTO(RolePreference entity);

    @Mapping(target = "id", ignore = true) // id is generated by DB
    @Mapping(target = "createdAt", expression = "java(java.time.LocalDateTime.now())")
    RolePreference toEntity(RolePreferenceRequestDTO dto);
}
